### ISSUE TITLE
After all guides reach ideation stage, rewrite Todos app following recommendations to the letter

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#48]
We need to do this to get a feeling for what an app looks like when it follows all of these recommendations. Some apps we have built in the past are pretty close, but we need to make sure everything we say meshes well together and ends up with an app that feels good.

### Todos
- [ ] Move files to packages + rename according to our scheme.
  - [x] Basic package-per route + collection
  - [x] Place global CSS and resources in the right spots
  - [ ] Ensure names fit our scheme
- [x] Switch to flow router
- [ ] Modularize properly (stores etc)
- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

**Comment by tmeasday** [comment]
I added some todos (haha) to the summary, will expand as I get to it.

**Comment by tmeasday** [comment]
https://github.com/meteor/todos

**Comment by dburles** [comment]
Interesting, which parts of the app are moving to packages?

**Comment by tmeasday** [comment]
all the parts

**Comment by tmeasday** [comment]
Closing this, tracking against the todos repo now
